# -*- coding: utf-8 -*-
"""Import and helper function.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/118tCIkRq8FjFQaanNsR7CwscG9g8AajR
"""

#include <iostream>
#include <vector>
#include <random>
#include <cmath>
#include <cuda_runtime.h>

// ==================================================================================
// Configuration and Helper Macro
// ==================================================================================

// Matrix dimensions
const int SEQ_LEN = 1024;
const int D_K = 64;

// Tile width for the optimized kernel. 16 or 32 are common values.
#define TILE_WIDTH 16

// CUDA Error checking macro
#define CHECK_CUDA(call) do { cudaError_t err = call; if (err != cudaSuccess) { fprintf(stderr, "CUDA Error at %s:%d: %s\n", __FILE__, __LINE__, cudaGetErrorString(err)); exit(EXIT_FAILURE); } } while (0)